version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    command: python3 app.py 
    networks:
      - app_net

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "sleep 10 && pytest"
    networks:
      - app_net
    depends_on:
      app:
        condition: service_healthy
networks:
    app_net:

